<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/bottles/bottle-1.glb --types
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Cylinder: THREE.Mesh;
			Plane: THREE.Mesh;
			Plane001: THREE.Mesh;
			Circle: THREE.Mesh;
			Circle001: THREE.Mesh;
			Cylinder001: THREE.Mesh;
			Cylinder002_1: THREE.Mesh;
			Cylinder002_2: THREE.Mesh;
			Cylinder003: THREE.Mesh;
		};
		materials: {
			['Material.001']: THREE.MeshStandardMaterial;
			['Material.002']: THREE.MeshStandardMaterial;
			Material: THREE.MeshStandardMaterial;
			['Material.004']: THREE.MeshPhysicalMaterial;
			Label: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/bottles/bottle-1.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cylinder.geometry}
			material={gltf.materials['Material.001']}
			position={[0, -1.71, 0]}
			rotation={[0, -1.08, 0]}
			scale={[0.74, 1, 0.74]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Plane.geometry}
			material={gltf.nodes.Plane.material}
			position={[0, 1.12, 0]}
			rotation={[0, -1.08, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Plane001.geometry}
			material={gltf.nodes.Plane001.material}
			position={[0, 1.01, 0]}
			rotation={[0, -1.08, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Circle.geometry}
			material={gltf.materials['Material.002']}
			position={[0, 0.88, 0]}
			rotation={[0, -1.08, 0]}
			scale={[0.47, 0.46, 0.47]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Circle001.geometry}
			material={gltf.materials.Material}
			position={[0, 1.32, 0]}
			rotation={[0, -1.08, 0]}
			scale={0.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cylinder001.geometry}
			material={gltf.materials['Material.004']}
			position={[0, -1.06, 0]}
			rotation={[0, -1.08, 0]}
			scale={[0.73, 0.98, 0.73]}
		/>
		<T.Group position={[0, -1.71, 0]} rotation={[0, -1.08, 0]} scale={[0.74, 1, 0.74]}>
			<T.Mesh
				geometry={gltf.nodes.Cylinder002_1.geometry}
				material={gltf.materials['Material.001']}
			/>
			<T.Mesh geometry={gltf.nodes.Cylinder002_2.geometry} material={gltf.materials.Label} />
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.Cylinder003.geometry}
			material={gltf.materials.Label}
			position={[0, -1.71, 0]}
			rotation={[0, -1.08, 0]}
			scale={[0.74, 1, 0.74]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
