<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/models/chair.glb --types
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		mainColor,
		accentColor,
		mainMaterial,
		accentMaterial,
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Object_2: THREE.Mesh;
			Object_3: THREE.Mesh;
		};
		materials: {
			metal: THREE.MeshStandardMaterial;
			wood: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/chair.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]}>
			<T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials[accentMaterial]}>
				<!-- <T.MeshPhysicalMaterial color={accentColor.color} roughness={0.5} metalness={0.9} /> -->
			</T.Mesh>
			<T.Mesh
				material.color="#fff"
				geometry={gltf.nodes.Object_3.geometry}
				material={gltf.materials[mainMaterial]}
			>
				<!-- <T.MeshPhysicalMaterial roughness={0.2} color={mainColor.color} /> -->
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
