<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/bottles/serum.glb --types
-->

<script lang="ts">
	import * as THREE from 'three';

	// let lavendarTexture = $state(null);
	import {
		DoubleSide,
		TextureLoader,
		MeshBasicMaterial,
		SRGBColorSpace,
		RepeatWrapping
	} from 'three';
	import { onMount, type Snippet } from 'svelte';
	import { T, type Props, useLoader, useRenderer } from '@threlte/core';
	import { useGltf, ImageMaterial, useTexture, SVG } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		label,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const renderer = useRenderer();
	const lavendarTexture = $derived.by(async () => {
		// const png = await svgToDataUrl(lavendarLabel, { format: 'png', width: 1500 });
		if (!label) return null;

		const loader = new TextureLoader();
		const texture = loader.load(label);
		texture.colorSpace = SRGBColorSpace;
		texture.flipY = false;
		// texture.anisotropy = renderer.renderer.getMaxAnisotropy();
		texture.generateMipmaps = false;
		return texture;
	});

	const cylinder = new THREE.CylinderGeometry(5, 5, 20, 32);
</script>

<T.Group bind:ref dispose={false} {...props}>
	<T.Group position={[0, 0, 0]} scale={1}>
		<!-- {#await lavendarTexture then map} -->
		<T.Mesh geometry={cylinder} scale={1}>
			<T.MeshPhysicalMaterial roughness={0.5} />
		</T.Mesh>
		<!-- {/await} -->
	</T.Group>

	{@render children?.({ ref })}
</T.Group>
